# Generated by Django 2.0 on 2018-01-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('ordering', models.IntegerField(default=1)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['ordering', 'expiry_date'],
            },
        ),
    ]
